export const FETCH_QUIZES_START = "FETCH_QUIZES_START"
export const FETCH_QUIZES_SUCCESS = "FETCH_QUIZES_SUCCESS"
export const FETCH_QUIZES_ERROR = "FETCH_QUIZES_ERROR"

export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS"
export const QUIZ_SET_STATE = "QUIZ_SET_STATE"
export const QUIZ_FINISHED = "QUIZ_FINISHED"
export const NEXT_QUESTION = "NEXT_QUESTION"
export const RETRY_QUIZ = "RETRY_QUIZ"

export const RESET_QUIZ_CREATION = "RESET_QUIZ_CREATION"
export const CREATE_QUIZ_QUESTION = "CREATE_QUIZ_QUESTION"

export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_LOGOUT = "AUTH_LOGOUT"